function getLEVE()
    return tonumber(GetNodeText("GuildLeve", 5, 2))
end

notifySound = " <se.10>"

yield ("/at enable")
yield ("/e ------------------------------------------------------------------------------")
yield ("/e このスクリプトは、TextAdvanceと併用する為")
yield ("/e こちら側で自動的に ON にさせて頂きました")
yield ("/e ------------------------------------------------------------------------------")
yield ("/wait 1")

yield ("/target グリッグ")
yield ("/send NUMPAD0")
yield ("/waitaddon SelectString")
yield ("/click select_string2")
yield ("/waitaddon JournalDetail")
getLEVE()
currentleve = getLEVE()

yield ("/wait 1")
yield ("/e ------------------------------------------------------------------------------")
yield ("/e これはキャロットラペ専用のスクリプトです")
yield ("/e 自動納品の最中は、なるべく操作しないようにお願いします by 製作者 " .. notifySound)
yield ("/e ------------------------------------------------------------------------------")
yield ("/wait 1")
yield ("/e あなたが所持しているリーブ券の枚数:" .. currentleve)
for i =1, currentleve do
    if i == 1 then
        yield ("/e タスク進行中 | " .. i .. "/" ..currentleve)
        yield ("/click journal_detail_accept")
        yield ("/wait 1")
        yield ("/send ESCAPE")
        yield ("/waitaddon SelectString")
        yield ("/click select_string4")
        yield ("/wait 1")
        yield ("/target アルダイルン")
        yield ("/send NUMPAD0")
        yield ("/waitaddon SelectIconString")
        yield ("/click select_icon_string2")
        yield ("/waitaddon SelectYesno")
        yield ("/click select_yes")
        yield ("/wait 1")
    else
        yield ("/e タスク進行中 | " .. i .. "/" ..currentleve)
        yield ("/target グリッグ")
        yield ("/send NUMPAD0")
        yield ("/waitaddon SelectString")
        yield ("/click select_string2")
        yield ("/waitaddon JournalDetail")
        yield ("/click journal_detail_accept")
        yield ("/wait 1")
        yield ("/send ESCAPE")
        yield ("/waitaddon SelectString")
        yield ("/click select_string4")
        yield ("/wait 1")
        yield ("/target アルダイルン")
        yield ("/send NUMPAD0")
        yield ("/waitaddon SelectIconString")
        yield ("/click select_icon_string2")
        yield ("/waitaddon SelectYesno")
        yield ("/click select_yes")
        yield ("/wait 1")
    end
end
yield ("/e すべてのタスクが完了しました" .. notifySound)